on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      trigger_build:
        description: "internal: do not check"
        required: false
        default: false
        type: boolean

permissions: read-all

concurrency: "e2e.delegator-generic.workflow_dispatch.branch1.default.slsa3"

env:
  GH_TOKEN: ${{ secrets.E2E_GENERIC_TOKEN }}
  ISSUE_REPOSITORY: slsa-framework/slsa-github-generator

jobs:
  # Bootstrap
  ################################################################################

  bootstrap:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && !inputs.trigger_build)
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      # Bumps the package version pushes, creates a git tag, and pushes the tag.
      - run: ./.github/workflows/scripts/e2e-bootstrap.sh

  if-bootstrap-failed:
    runs-on: ubuntu-latest
    needs: [bootstrap]
    if: always() && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && !inputs.trigger_build)) && needs.bootstrap.result != 'success'
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - run: ./.github/workflows/scripts/e2e-report-failure.sh

  # Main workflow
  ################################################################################

  # Shim determines if the rest of the workflow should run.
  # NOTE: it should only use the `if` to determine this and all downstream jobs
  #      should depend on this job.
  shim:
    # NOTE: this must be kept in sync with the if-failed job.
    if: github.event_name == 'workflow_dispatch' && inputs.trigger_build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event: ${GITHUB_EVENT_NAME}"
          echo "ref: ${GITHUB_REF}"

  build:
    needs: [shim]
    permissions:
      id-token: write # For signing
      contents: write # For asset uploads
      packages: write # To write to github packages
      actions: read
    uses: slsa-framework/example-trw/.github/workflows/builder_high-perms_slsa3.yml@v0.0.1
    with:
      artifact: my-artifact
      content: "hello world delegator_generic_slsa3"
    secrets:
      # NOTE: this password is set to 'delegator-password'.
      password: ${{ secrets.DELEGATOR_PASSWORD }}

  verify:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/download-artifact@bb3fa7fd35ab8113a980912eb9f59b846d14e3ff
        with:
          name: "${{ needs.build.outputs.artifact }}" # NOTE: This is 'my-artifact'.
      - uses: slsa-framework/example-trw/high-perms/actions/download/attestation@v0.0.1
        with:
          name: "${{ needs.build.outputs.provenance-download-name }}"
          sha256: "${{ needs.build.outputs.provenance-download-sha256 }}"
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: "1.21"
      - env:
          BINARY: "${{ needs.build.outputs.artifact }}"
          PROVENANCE: "${{ needs.build.outputs.provenance-download-name }}/${{ needs.build.outputs.artifact }}.build.slsa" # This is defined by the builder.
          BUILDER_ID: "https://github.com/slsa-framework/example-trw/.github/workflows/builder_high-perms_slsa3.yml@v0.0.1"
        run: ./.github/workflows/scripts/e2e.delegator.default.verify.sh

  if-succeeded:
    runs-on: ubuntu-latest
    needs: [build, verify]
    if: needs.build.result == 'success' && needs.verify.result == 'success'
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - run: ./.github/workflows/scripts/e2e-report-success.sh

  if-failed:
    runs-on: ubuntu-latest
    needs: [build, verify]
    if: always() && github.event_name == 'workflow_dispatch' && inputs.trigger_build && (needs.build.result != 'success' || needs.verify.result != 'success')
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - run: ./.github/workflows/scripts/e2e-report-failure.sh
