name: yamllint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  # Needed to check out the repo.
  contents: read

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - env:
          YAMLLINT_VERSION: "1.26.3"
        run: |
          set -euo pipefail

          # Install yamllint
          pip install "yamllint==${YAMLLINT_VERSION}"

          # Run yamllint
          make yamllint
