# This workflow deletes old releases created by e2e tests to keep the number
# managable.

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions: read-all

env:
  GH_TOKEN: ${{ secrets.E2E_GENERIC_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to delete tags
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Delete old releases
        id: build
        run: ./.github/workflows/scripts/e2e-delete-old-releases.sh
